### PR TITLE
Proper cleanup when removing html component

### PR DESCRIPTION
**Pull request by vincentfretin**
I'm using solidjs to create an ui on the wrist. I render the dom element when necessary when entering vr mode, and setting the html component on the wrist at that moment. When I remove the dom element when exiting vr mode, I also remove the html component, but I got the following error because the setTimeout was run after the the dom element was removed:
```
core:a-node:error Failure loading node:   DOMException: Failed to execute 'arcTo' on 'CanvasRenderingContext2D': The radius provided (-2) is negative.
    at r (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:2333)
    at e (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:4782)
    at e (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:5734)
    at e (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:5734)
    at s (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:5769)
    at new i (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:674)
    at new t (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:73)
    at n.update (https://192.168.1.15:8080/cdn/npm/aframe-htmlmesh@2.0.0/build/aframe-html.min.js:1:6387)
    at n.initComponent (https://192.168.1.15:8080/cdn/gh/aframevr/aframe@75898345005d43d2d48f6ddd4249aa93d7676613/dist/aframe-master.min.js:2:412843)
    at n.updateProperties (https://192.168.1.15:8080/cdn/gh/aframevr/aframe@75898345005d43d2d48f6ddd4249aa93d7676613/dist/aframe-master.min.js:2:412373)
```

There is actually a clearTimeout already in HTMLMesh dispose but you didn't call `mesh.dispose()` in your `remove()`.
I also fixed removing all the listeners.

### CODE REVIEW

**Comment by vincentfretin** [comment]
It's weird I can't make my exit immersive button work, the radio boxes are ok, but the onclick on my button doesn't work. If I change my button to a radio the onclick works. I'm not sure if the issue is related to my solidjs/tailwindcss ui or latest changes in aframe-htmlmesh 2.0.0 or this PR. I'll try to update your aframe-xr-boilerplate with this PR to see if I reproduce.
Please wait before merging.

**Comment by AdaRoseCannon** [comment]
Super, thank you so much!

**Comment by vincentfretin** [comment]
For the issue I'm having with the button that is not clickable. I did an intense debugging session yesterday, it seems I only have mouseenter/mouseleave events (and the fake mousemove event you create), but not any mouseup, mousedown, click events. The radio change when I press trigger on the label, but I only see the mousemove event on it, it's weird. I surely did something wrong somewhere or there is a conflict between some other components. I'll do another debugging session, I think I'll update your aframe-xr-boilerplate to see if I reproduce there or not, if I don't reproduce it will mean it's specific to my project.
While debugging I discovered why my sphere cursor wasn't working, I'll create a PR just for this.

**Comment by AdaRoseCannon** [comment]
Thanks for looking into it

**Comment by vincentfretin** [comment]
Oh I was probably tired yesterday, I do see the mousedown mouseup, click events, it's just I have lots of mousemove logs after that. I added logs everywhere, I see that `element.dispatchEvent( new MouseEvent( event, mouseEventInit ) );` is triggered on the button, but it has no effect. I'm wondering if it's an issue with that event and how solidjs handle onClick on button at this point. I'll test on your example without solidjs to confirm.

click at x=0.3652705179422506 y=0.7649406967994908
div DOMRect {bottom: 502.5, height: 171.9140625, left: 15.99609375, right: 278.33984375, top: 330.5859375, width: 262.34375, x: 15.99609375, y: 330.5859375}
clientX 111.700875701 element.offsetWidth 262 element.offsetLeft 16
clientY 462.56979985 element.offsetHeight 172 element.offsetTop 331
button click at rect.left=31.9921875 x=111.82253119141231 rect.right=204.9609375 rect.top=450.52734375 y=462.0900002583812 rect.right=486.50390625
so all the coordinates seem fine here.

**Comment by vincentfretin** [comment]
huh, the issue was really a compatibility between this produced click MouseEvent event and solidjs
This doesn't work in VR:
```
<button
  onClick={() => {
    AFRAME.scenes[0].exitVR();
  }}
  class="btn mt-4 bg-red-600 hover:bg-red-700 focus:bg-red-700 active:bg-red-800"
>Exit Immersive</button>
```

This works in VR:
```
<button
  onClick="AFRAME.scenes[0].exitVR();"
  class="btn mt-4 bg-red-600 hover:bg-red-700 focus:bg-red-700 active:bg-red-800"
>Exit Immersive</button>
```

Both works on desktop.

**Comment by vincentfretin** [comment]
About sphere cursor. The issue I had is that I have `cursor="rayOrigin:mouse"` on a-scene for desktop.
The intersection logic don't work at all because the activeRaycaster is the one on a-scene, not the one on the hand.
You see the following events order:
- mouseenter from hand
- mouseenter from a-scene
- mousemove with {cursorEl: a-scene, intersection: null}
- mouseleave from hand
- mouseleave from a-scene

At first I added `if (evt.stopPropagation) evt.stopPropagation();` I'll swear this fix worked at one point but maybe I commented `cursor="rayOrigin:mouse"` on a-scene when I was testing... 
Anyway it's better that I simply remove this cursor on a-scene on enter-vr, and add it back when exit-vr, this is what I did. So no PR needed for this issue.

**Comment by AdaRoseCannon** [comment]
This is sounding very similar to an issue I was having with AFrame and started a PR for but it turns out the issue runs deep: 
https://github.com/aframevr/aframe/issues/5075

https://github.com/aframevr/aframe/pull/5076

**Comment by vincentfretin** [comment]
Yes indeed this is the exact issue.

Removing the cursor component on enter-vr is not enough, on first mousenter I don't see the sphere. On second mouseenter I see it. If I also remove the raycaster on a-scene on enter-vr, then the sphere shows up properly on first mouseenter.
It's best to avoid unnecessary work, so better remove what I don't use when in vr.
Same on desktop, I need to verify but I guess the raycaster on hands are active for nothing.

**Comment by dmarcos** [comment]
A-Frame should disable behavior that doesn't make sense in VR. Should a cursor with rayOrigin: mouse be inert when entering VR? Should a cursor rayOrigin: mouse on the scene make disable all other cursors?

**Comment by vincentfretin** [comment]
I see the discussion continued here https://github.com/aframevr/aframe/issues/5075#issuecomment-1341934201
I would prefer aframe doesn't do clever things like disabling cursor/raycaster on other entities automatically, so introducing inter-dependencies between cursor/raycaster instances, this will be even harder to debug why things don't work in my opinion.
The cursor with rayOrigin: mouse is just a special case, you may have a cursor with rayOrigin: entity on desktop and would maybe want it to be inactive in VR. I think enabling/disabling a component should be the app responsibility, not the library.

**Pull request merged**
